name: PRERELEASE
on:
  workflow_dispatch:
    branches:
      - prerelease
  pull_request:
    types:
      - closed

permissions: {}
jobs:
  version:
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/prerelease'
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          key: node-modules-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
          path: "**/node_modules"

      - name: Install dependencies
        run: npm ci

      - name: Enter prerelease mode
        run: npm run changeset pre enter next || true

      - name: Check should create release
        id: should-create-release
        run: |
          if [[ $(cat ./.changeset/pre.json | grep -m 1 mode | sed 's/[^a-z]//g') == *"pre"* ]]; then
            echo "RESULT=true" >> $GITHUB_OUTPUT
          else
            echo "RESULT=false" >> $GITHUB_OUTPUT
          fi
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        if: steps.should-create-release.outputs.RESULT == 'true'
        uses: changesets/action@v1
        with:
          publish: npm run changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit changes
        if: steps.update-lock-file.outputs.IS_CHANGED == 'true'
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git add .
          git commit -m "chore: update changes" -s
          git push --follow-tags

  release:
    if: github.event.pull_request.merged == true && github.base_ref == 'prerelease' && github.head_ref == 'changeset-release/prerelease'
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          key: node-modules-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
          path: "**/node_modules"

      - name: Install dependencies
        run: npm ci

      - name: Enter prerelease mode
        run: npm run changeset pre enter next || true

      - name: Check should create release
        id: should-create-release
        run: |
          if [[ $(cat ./.changeset/pre.json | grep -m 1 mode | sed 's/[^a-z]//g') == *"pre"* ]]; then
            echo "RESULT=true" >> $GITHUB_OUTPUT
          else
            echo "RESULT=false" >> $GITHUB_OUTPUT
          fi
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        if: steps.should-create-release.outputs.RESULT == 'true'
        uses: changesets/action@v1
        with:
          publish: npm run changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Exit prerelease mode
        id: exit-prerelease-mode
        run: |
          rm ./.changeset/pre.json
          if [[ $(git status --porcelain | grep -m 1 pre.json | sed 's/[^a-z]\-//g') == *"pre.json"* ]]; then
            echo "IS_CHANGED=true" >> $GITHUB_OUTPUT
          else
            echo "IS_CHANGED=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit pre.json
        if: steps.exit-prerelease-mode.outputs.IS_CHANGED == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .changeset/pre.json
          git commit -m "chore: exit prerelease mode" -s
          git push origin prerelease
