name: Tagging And Release
on:
  pull_request:
    types:
      - closed

permissions: {}

jobs:
  tagging-and-release:
    if: github.event.pull_request.merged == true && github.base_ref == 'main' && github.head_ref == 'changeset-release/main'
    permissions:
      contents: write # to create release (changesets/action)
    runs-on: ubuntu-24.04
    steps:
      - name: Set git user
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

       - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          key: node-modules-${{ hashFiles('package.json') }}-${{ hashFiles('pnpm-lock.yaml') }}
          path: "**/node_modules"

      - name: Get tag version
        id: get-tag-version
        run: |
          VERSION=$(cat ./apps/adonis-server/package.json | grep -m 1 version | sed 's/[^0-9.]//g')
          APP_NEW_TAG=v$VERSION
          echo "APP_NEW_TAG=$APP_NEW_TAG" >> $GITHUB_ENV
          echo '::set-output name=newTag::'$APP_NEW_TAG
          echo '::set-output name=version::'$VERSION
          echo "New release tag is $APP_NEW_TAG"
      - name: Check should create release
        id: should-create-tag
        run: |
          if [ $(git tag -l "$APP_NEW_TAG") ]; then
            echo '::set-output name=APP_TAG_EXISTS::true'
          else
            echo '::set-output name=APP_TAG_EXISTS::false'
          fi
      - name: Release apps and packages
        if: steps.should-create-tag.outputs.APP_TAG_EXISTS == 'false'
        uses: changesets/action@v1
        with:
          publish: pnpm changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract release notes
        if: steps.should-create-tag.outputs.APP_TAG_EXISTS == 'false'
        id: extract-release-notes
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: "reaction@${{ steps.get-tag-version.outputs.version }}"
          doNotFailIfNotFound: true

      - name: Create tag
        if: steps.extract-release-notes.outputs.body != ''
        run: |
          git tag -a $APP_NEW_TAG -m "chore(release): $APP_NEW_TAG [skip ci]"
          git push origin $APP_NEW_TAG
          echo "Create tag success: $APP_NEW_TAG"

      - name: Create Release
        if: steps.extract-release-notes.outputs.body != ''
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.extract-release-notes.outputs.body }}
          tag_name: ${{ steps.get-tag-version.outputs.newTag }}
          draft: false
          prerelease: false